export const PILLARS = [
  {
    id: 'training',
    wc: 'var(--lime)',
    en: 'WEIGHT TRAINER',
    doodle: 'Grid',
    strip: {
      title: 'منهجية التدريب — سُلَّم الوزن',
      steps: [
        { icon: 'Pen', title: 'التقطيع', text: 'حوّل البار لبصمة ● و ▬' },
        { icon: 'Star', title: 'التكافؤ', text: 'حروف مختلفة، بصمة واحدة = توازن' },
        { icon: 'Grid', title: 'المطابقة', text: 'قارن بصمتك بالقالب مقطعًا بمقطع' },
        { icon: 'Headphones', title: 'المحاذاة', text: 'الثقل ▬ على ضربة البيت = فلو يطق' },
      ],
    },
    num: '01',
    title: 'التدريب',
    tagline: 'صقل المهارة بمنهج علمي',
    motif: '● ▬ ● ● ▬',
    planned: ['تمارين التقطيع والبصمة ●/▬', 'مسار حروف القافية الستة', 'التدرب على مسارات معزولة حقيقية', 'مؤشرات تقدم حقيقية'],
    step: 'يُبنى في المرحلة 6',
  },
  {
    id: 'studio',
    wc: 'var(--mango)',
    en: 'CHANNEL STUDIO',
    doodle: 'Pen',
    strip: {
      title: 'كيف تعمل معاينة القافية؟',
      steps: [
        { icon: 'Pen', title: 'اكتب البار', text: 'كل سطر = بار' },
        { icon: 'Search', title: 'المحرك يلقط الروي', text: 'آخر حرف صحيح في البار' },
        { icon: 'Spray', title: 'نفس الروي = نفس اللون', text: 'العائلات تتلون تلقائيًا' },
      ],
    },
    num: '02',
    title: 'الاستوديو الإبداعي',
    tagline: 'مساحة الكتابة والصنعة اليومية',
    motif: '▬ ● ▬ ▬ ●',
    planned: ['محرر البارات بالتلوين القافوي الحي', 'أرشيف التمثيلات (نظام المزيج)', 'القوالب البصرية للمقاطع', 'استوديو الفلو التفاعلي'],
    step: 'يُبنى في المراحل 2 و4ج و5',
  },
  {
    id: 'analysis',
    wc: 'var(--violet)',
    en: 'BEAT ANALYZER',
    doodle: 'Boombox',
    strip: {
      title: 'خط تحليل البيت — كما سيُبنى',
      steps: [
        { icon: 'Cassette', title: 'ارفع البيت', text: 'أي تراك من مكتبتك' },
        { icon: 'Boombox', title: 'عزل ٣ مسارات', text: 'درامز · باص · ميلودي' },
        { icon: 'Grid', title: 'شبكة الضربات', text: 'خريطة الفراغات جاهزة للكتابة' },
      ],
    },
    num: '03',
    title: 'التحليل الموسيقي',
    tagline: 'تشريح البيت حتى آخر ضربة',
    motif: '● ● ▬ ● ▬',
    planned: ['العزل الثلاثي: درامز / باص / ميلودي', 'شبكة الإيقاع وخريطة الفراغات', 'مسار الميلودي ومنحنى الطاقة', 'ملف Beat Profile الموحد'],
    step: 'يُبنى في المراحل 4أ و4ب',
  },
  {
    id: 'library',
    wc: 'var(--gold)',
    en: 'SAMPLE LIBRARY',
    doodle: 'Notebook',
    strip: {
      title: 'مستودعك — دفتر بارات لا يضيع',
      steps: [
        { icon: 'Notebook', title: 'احفظ البار', text: 'سطر واحد وزر حفظ' },
        { icon: 'Search', title: 'ابحث فورًا', text: 'بحث حي في كل شيء' },
        { icon: 'Star', title: 'شارة الروي', text: 'كل بار يعرف قافيته' },
      ],
    },
    num: '04',
    title: 'المستودع المعرفي',
    tagline: 'ترسانتك: بارات ومراجع وبحث',
    motif: '▬ ▬ ● ▬ ●',
    planned: ['مكتبة البارات المنقولة والجديدة', 'المراجع: منهجية الوزن، أسرار الحروف، وغيرها', 'بحث ذكي يربط كل شيء', 'قاعدة letter_semantics'],
    step: 'يُبنى في المرحلة 2 والخطوة 65',
  },
  {
    id: 'prosody',
    wc: 'var(--teal)',
    en: 'PROSODY LAB',
    doodle: 'Wave',
    strip: {
      title: 'كيف يعمل مختبر النبض العروضي؟',
      steps: [
        { icon: 'Wave', title: 'ابنِ البصمة', text: 'أضف - و~ لتكتشف اسم القدم' },
        { icon: 'Star', title: 'شخّص النهاية', text: 'مذكرة أم مؤنثة؟ اعرف الأثر' },
        { icon: 'Grid', title: 'امسح التكرار', text: '٩ مستويات بنيوية للتتبع' },
        { icon: 'Notebook', title: 'راجع القاموس', text: '٣٠ قدمًا عروضية مصنفة' },
      ],
    },
    num: '05',
    title: 'مختبر النبض العروضي',
    tagline: 'تصنيف الأقدام الشعرية ونهايات الأبيات ومصفوفة التكرار البنيوي',
    motif: '- ~ - ~ -',
    planned: [],
    step: '',
  },
]
